import React from 'react'
import Paragraph from '../components/paragraph';

export default class Home extends React.Component {
  constructor(props) {
    super(props);
    this.content = [
      {
        title: '',
        text: <p>Das Internet und insbesondere soziale Netzwerke sowie Instant Messaging Dienste haben unsere Kommunikation stark verändert. Durch ihre Hilfe ist es uns möglich sich jederzeit mit Bekannten auszutauschen oder persönliche Meinungen und Erlebnisse zu teilen. Allerdings zeigt die Forschung, dass eine exzessive Nutzung dieser Anwendungen auch negative Effekte haben kann.</p>
      },
      {
        title: 'Bin ich süchtig nach Social Media?',
        text: <p>In der Forschung gibt es mittlerweile viele Hinweise darauf, dass die übermäßige Nutzung von Online-Angeboten negative Auswirkungen auf Nutzer*innen haben kann. Es wird dabei davon ausgegangen, dass nicht das Internet selbst ausschlaggebend ist, sondern die einzelnen Anwendungen, die jemand benutzt [<a href="#1">1</a>],  zum Beispiel Online-Games wie World of Warcraft oder soziale Netzwerke wie Instagram oder Facebook. Ein weiterer Diskussionspunkt ist der Begriff "Sucht". Seit diesem Jahr, wird Onlinespielsucht von der WHO als Krankheit anerkannt [<a href="#2">2</a>]. Die Nutzung von sozialen Netzwerken oder Messenger Anwendungen wurde aber noch nicht genug untersucht, weshalb auch nicht offiziell von einer social networking Sucht gesprochen werden kann. Oft wird dafür "problematische Nutzung" verwendet [<a href="#3">3</a>].<br/>Personen, deren Nutzung von sozialen Netzwerken als problematisch angesehen werden kann, verbringen so viel Zeit auf Social Media Plattformen, dass dadurch andere soziale Aktivitäten oder Leistungen in der Schule oder im Beruf beeinträchtigt werden. Außerdem kann sich die Gesundheit und das Wohlbefinden von betroffenen Personen verschlechtern [<a href="#4">4</a>]. Verschiedene Studien zeigen auch, dass psychopathologische Eigenschaften wie Depression oder soziale Angst in Zusammenhang mit problematischer Nutzung von sozialen Netzwerken stehen [<a href="#3">3</a>]. Allerdings ist hierbei nicht klar in welche Richtung diese Effekte wirken. Es könnte zum Beispiel sein, dass Personen, die Depressionen haben, dazu tendieren Facebook oder Instagram besonders stark zu nutzen, weil sie hoffen so ihre bestehenden Probleme bewältigen zu können. Andererseits könnte es auch sein, dass die übermäßige Nutzung von diesen Anwendungen die Depressionen auslöst oder verstärkt.</p>
      },
      {
        title: 'Warum sind soziale Medien so anziehend?',
        text: <p>Soziale Medien können, wenn sie in einem gesunden Umfang genutzt werden, unseren Alltag bereichern. Aber warum ist es manchmal so schwer sich davon zu lösen und warum kann der Drang die Anwendungen zu nutzen bei manchen Personen so stark werden, dass sie potenzielle Nebenwirkungen außer Acht lassen?<br/>Ein Grund für die hohe Anziehungskraft könnte sein, dass das Teilen von persönlichen Informationen mit anderen Menschen von Natur aus belohnend für uns ist. Studien zeigen, dass Selbstoffenbarung zu erhöhter Aktivität im Belohnungszentrum des Gehirns führt [<a href="#5">5</a>]. Selbstoffenbarung ist ein elementarer Bestandteil von sozialen Medien. Es ist extrem einfach Bilder oder andere Arten von Nachrichten mit anderen Personen zu teilen. Außerdem kann man jederzeit und von überall aus Beiträge veröffentlichen. Social Media Anwendungen befriedigen in ihrem Kern also das menschliche Bedürfnis nach sozialem Austausch.<br/>Doch nicht nur das Teilen von Informationen wird durch soziale Medien vereinfacht, sondern auch das reagieren darauf. Andere Personen können öffentliche Beiträge kommentieren, weiter teilen oder liken. Dabei kann sowohl das Geben von likes als auch das Erhalten von likes ein Belohnungsgefühl auslösen. Studien zeigen, dass Likes geben und bekommen Aktivität in Gehirnregionen auslöst, die mit Belohnung in Verbindung stehen [<a href="#6">6</a>, <a href="#7">7</a>].</p>
      },
      {
        title: 'Der Flow in sozialen Netzwerken',
        text: <p>Flow-Erleben beschreibt einen Zustand, in dem man völlig in eine bestimmte Tätigkeit vertieft ist. Dabei sind sowohl die eigenen Fähigkeiten als auch die Anforderungen der Tätigkeit entscheidend. Ist die Aufgabe zu schwierig fühlt man sich überfordert, ist die Aufgabe zu einfach fühlt man sich unterfordert. Nur wenn die Anforderungen mit den eigenen Fähigkeiten übereinstimmen, entsteht das Flow-Erleben [<a href="#8">8</a>]. Grundsätzlich ist dieser Zustand etwas positives, es wird beschrieben, dass dadurch Glück entsteht. Im Kontext von digitalen Anwendungen könnte dieser Zustand aber gefährlich sein, weil man so vielleicht länger Zeit auf einer Seite verbringt, als man ursprünglich vorhatte. Wer sich im Flow befindet, kann nämlich oft die Zeit nicht mehr richtig einschätzen.<br/>Social Media Anwendungen können Flow durch die Tatsache erreichen, dass meist endlos gescrollt werden kann [<a href="#9">9</a>]. Zum Beispiel bietet Instagram eine "entdecken" Seite, auf der den Nutzer*innen Beiträge vorgeschlagen werden. Wenn man sich diese Beiträge ansieht, gibt es nie eine Unterbrechung oder einen Punkt, an dem man kurz gestoppt wird. Es wird außerdem angenommen, dass hierbei auch eine Form von Konditionierung (Lernprozesse, bei denen man sich an bestimmte Belohnungen oder Bestrafungen gewöhnt) auftritt. Da man in den meisten Fällen immer wieder auf interessante Beiträge stößt, wird es schwer aufzuhören, weil man das Gefühl hat, dass der nächste gute Beitrag nicht mehr weit sein kann. Ähnliche Effekte können auch beim Glücksspiel beobachtet werden [<a href="#10">10</a>].<br/>Unterstützt wird das endlose scrollen durch komplexe Algorithmen. Soziale Netzwerke wie Instagram und Facebook zeichnen alle unsere Aktivitäten, von Likes, über Kommentare, bis zu der Zeit, die wir auf bestimmten Seiten oder Beiträgen verbringen, auf [<a href="#11">11</a>]. Durch die Analyse dieser Daten können sie genau herausfinden, welche Präferenzen die Nutzer*innen haben und können die angezeigten Beiträge dementsprechend darauf ausrichten. Man sieht also nur das was man sehen will [<a href="#9">9</a>].</p>
      },
      {
        title: 'Nutzer*innen in eine Richtung nudgen',
        text: <p>Nudging bedeutet, dass die Umgebung einer bestimmten Situation leicht geändert wird, um das Verhalten von Personen zu beeinflussen, ohne dabei etwas zu verbieten [<a href="#12">12</a>]. Man soll sozusagen leicht in eine bestimmte Richtung geschubst werden. Zum Beispiel werden mehr gesunde Lebensmittel gekauft, wenn diese in der Nähe der Kasse platziert werden [<a href="#13">13</a>].<br/>Instant Messaging Anwendungen wie WhatsApp nudgen uns dazu die Plattform möglichst oft zu nutzen und möglichst schnell auf eingehende Nachrichten zu antworten [<a href="#9">9</a>]. Wenn jemand eine Nachricht verschickt, sieht er zuerst zwei graue Häkchen, wenn die Nachricht angekommen ist. Sobald die empfangende Person die Nachricht gelesen hat, werden die Häkchen blau angezeigt. Dadurch entsteht sozialer Druck bei der Person, die die Nachricht gelesen hat, weil diese weiß, dass die sendende Person die blauen Häkchen sehen kann. Außerdem konnte schon gezeigt werden, dass dieses Feature Stress auslösen kann [<a href="#14">14</a>].<br/>Auch die Standardeinstellungen von Apps können unsere Entscheidungen beeinflussen und uns unbewusst in eine Richtung nudgen. Im Falle von WhatsApp sind die blauen Häkchen standardmäßig eingestellt, was dazu führen könnte, dass viele Nutzer*innen die Option aktiv lassen, zum Beispiel weil sie nicht wissen, dass sie eine Wahl haben [<a href="#9">9</a>].</p>
      },
      {
        title: 'Die Angst etwas zu verpassen',
        text: <p>Die permanente Erreichbarkeit, die wir durch soziale Netzwerke und Instant Messaging Dienste erreicht haben, kann zu negativen Gefühlen führen, wenn dadurch FoMO (Fear of Missing Out) ausgelöst wird. FoMO umfasst einerseits den Gedanken, dass andere gute Erfahrungen machen und man davon ausgeschlossen ist. Man macht sich deswegen Sorgen oder hat sogar ein Angstgefühl. Andererseits beschreibt FoMO den konstanten Wunsch mit Bekannten in Verbindung zu bleiben. Dadurch soll die aufgebaute Angst wieder abgebaut werden. Oft äußert sich dieser Wunsch durch möglichst häufiges Überprüfen von sozialen Netzwerken und Messenger Anwendungen [<a href="#15">15</a>]. In der Forschung wird außerdem vermutet, dass FoMO ein Teil von problematischer Nutzung von sozialen Netzwerken sein kann [<a href="#16">16</a>]. In einem Artikel von Alutaybi et al. werden verschiedene Designaspekte von Social Media Anwendungen beschrieben, die zu FoMO beitragen können [<a href="#17">17</a>].<br/>Zum Beispiel beinhalten viele soziale Netzwerke zeitlich begrenzte Beiträge. Auf Snapchat, Instagram oder WhatsApp können Stories gepostet werden, die nur für eine bestimmte Zeit sichtbar sind und danach wieder gelöscht werden. Dadurch kann bei Nutzer*innen dieser Plattformen das Gefühl entstehen, man müsse möglichst oft nachschauen, ob es neue Stories gibt, um nichts zu verpassen.<br/>Auch Likes oder andere Formen von Reaktionen (z.B. Retweets) können FoMO auslösen. Wenn man keine Likes bekommt, von Personen, von denen man es eigentlich erwarten würde, kann das Gefühl entstehen nicht mehr beliebt oder interessant genug zu sein. Ähnliche Empfindungen kann auch die online Anzeige auslösen. Auf Messenger Apps wie WhatsApp wird angezeigt, wann jemand online ist. Wenn man sieht, dass jemand online ist, aber nicht auf die eigenen Nachrichten antwortet, fühlt man sich vielleicht ignoriert oder nicht wichtig genug.</p>
      },
      {
        title: 'Wie können soziale Medien zum besseren verändert werden?',
        text: <p>Betreiber von Social Media Anwendungen (z.B. Meta) profitieren davon, uns möglichst lange auf ihren Plattformen zu halten. Durch die Daten, die sie über uns sammeln, können sie nicht nur ihre eigenen Empfehlungssysteme immer genauer machen und immer besser auf uns zugeschnittene Seiten präsentieren, sondern sie können auch personalisierte Werbung schalten, wodurch sie Geld verdienen [<a href="#11">11</a>]. Trotzdem gibt es schon Beispiele von Features, die Eingeführt wurden, um Nutzer*innen davor zu schützen zu viel Zeit auf der Plattform zu verbringen. Zum Beispiel zeigt Instagram auf seiner Startseite eine Nachricht an, wenn man alle Posts der letzten zwei Tage gesehen hat [<a href="#18">18</a>]. Damit wurde zumindest für die Beiträge von Personen, denen man folgt, das endlose scrollen abgeschafft.<br/>Alutaybi et al. schlagen verschiedene Features vor, die FoMO reduzieren könnten [<a href="#19">19</a>]. Zum Beispiel könnten Filtermechanismen verwendet werden, um verschiedene Arten von Nachrichten zu klassifizieren, damit man besser einschätzen kann, welche Nachrichten wichtig sind und noch warten können. Wenn man zeitlich begrenzte Stories auf Snapchat oder Instagram speichern könnte (z.B. bis man das nächste Mal die Plattform öffnet), müsste man sich nicht mehr so viele Sorgen machen diese Beiträge zu verpassen. Das explizite Formulieren von Zeiten, zu denen man erreichbar oder nicht erreichbar ist, könnte dazu beitragen, dass sich andere Personen nicht mehr vernachlässigt fühlen. Außerdem könnte man automatische Antworten (so wie bei E-Mails) einbauen, die andere Personen darauf aufmerksam machen, dass man zurzeit verhindert ist.<br/>Zusammenfassend haben soziale Medien zwar viele Vorteile und können unseren Alltag bereichern, aber sie bieten auch Risiken, wenn wir die Kontrolle über unsere Nutzung verlieren. Oft werden für die Gestaltung von diesen Anwendungen Methoden verwendet, die in erster Linie darauf ausgelegt sind unsere Nutzungsdauer zu erhöhen, was eventuell zu solch einem Kontrollverlust beitragen kann. Es muss aber auch beachtet werden, dass die Forschung zu diesem Thema noch jung ist und dass es noch mehr Erkenntnisse braucht, um genau sagen zu können, welche Funktionen besonders schädlich für uns sein könnten.</p>
      },
      {
        title: 'Quellen',
        text: <div id="citationWrapper">
          <p id="1">[1] Brand, M., Young, K. S., Laier, C., Wölfling, K. & Potenza, M. N. (2016). Integrating psychological and neurobiological considerations regarding the development and maintenance of specific Internet-use disorders: An Interaction of Person-Affect-Cognition-Execution (I-PACE) model. Neuroscience & Biobehavioral Reviews, 71, 252–266. <a target="_blank" rel="noreferrer" href="https://doi.org/10.1016/j.neubiorev.2016.08.033">https://doi.org/10.1016/j.neubiorev.2016.08.033</a></p>
          <p id="2">[2] World Health Organisation. (2022). ICD-11. WHO. <a target="_blank" rel="noreferrer" href="https://icd.who.int/en">https://icd.who.int/en</a></p>
          <p id="3">[3] Wegmann, E. & Brand, M. (2019). A narrative Overview About Psychosocial Characteristics as Risk Factors of a Problematic Social Networks Use. Current Addiction Reports, 6(4), 402–409. <a href="https://doi.org/10.1007/s40429-019-00286-8" target="_blank" rel="norefferer">https://doi.org/10.1007/s40429-019-00286-8</a></p>
          <p id="4">[4] Andreassen, C. S. (2015). Online Social Network Site Addiction: A Comprehensive Review. Current Addiction Reports, 2(2), 175–184. <a href="https://doi.org/10.1007/s40429-015-0056-9" target="_blank" rel="norefferer">https://doi.org/10.1007/s40429-015-0056-9</a></p>
          <p id="5">[5] Tamir, D. I. & Mitchell, J. P. (2012). Disclosing information about the self is intrinsically rewarding. Proceedings of the National Academy of Sciences, 109(21), 8038–8043. <a href="https://doi.org/10.1073/pnas.1202129109" target="_blank" rel="norefferer">https://doi.org/10.1073/pnas.1202129109</a></p>
          <p id="6">[6] Sherman, L. E., Hernandez, L. M., Greenfield, P. M. & Dapretto, M. (2018). What the brain ‘Likes’: neural correlates of providing feedback on social media. Social Cognitive and Affective Neuroscience, 13(7), 699–707. <a href="https://doi.org/10.1093/scan/nsy051" target="_blank" rel="norefferer">https://doi.org/10.1093/scan/nsy051</a></p>
          <p id="7">[7] Sherman, L. E., Payton, A. A., Hernandez, L. M., Greenfield, P. M. & Dapretto, M. (2016). The Power of the Like in Adolescence. Psychological Science, 27(7), 1027–1035. <a href="https://doi.org/10.1177/0956797616645673" target="_blank" rel="norefferer">https://doi.org/10.1177/0956797616645673</a></p>
          <p id="8">[8] Csikszentmihalyi, M. (2022). Flow: The Psychology of Happiness (Rider Classics). Rider.</p>
          <p id="9">[9] Montag, C., Lachmann, B., Herrlich, M. & Zweig, K. (2019). Addictive Features of Social Media/Messenger Platforms and Freemium Games against the Background of Psychological and Economic Theories. International Journal of Environmental Research and Public Health, 16(14), 2612. <a href="https://doi.org/10.3390/ijerph16142612" target="_blank" rel="norefferer">https://doi.org/10.3390/ijerph16142612</a></p>
          <p id="10">[10] Harrigan, K. A. & Dixon, M. (2009). PAR Sheets, probabilities, and slot machine play: Implications for problem and non-problem gambling. Journal of Gambling Issues, 23, 81. <a href="https://doi.org/10.4309/jgi.2009.23.5" target="_blank" rel="norefferer">https://doi.org/10.4309/jgi.2009.23.5</a></p>
          <p id="11">[11] Montgomery, K. C. (2015). Youth and surveillance in the Facebook era: Policy interventions and social implications. Telecommunications Policy, 39(9), 771–786. <a href="https://doi.org/10.1016/j.telpol.2014.12.006" target="_blank" rel="norefferer">https://doi.org/10.1016/j.telpol.2014.12.006</a></p>
          <p id="12">[12] Thaler, R. H. & Sunstein, C. R. (2021). Nudge: The Final Edition (Revised Aufl.). Penguin Books.</p>
          <p id="13">[13] Kroese, F. M., Marchiori, D. R. & de Ridder, D. T. D. (2015). Nudging healthy food choices: a field experiment at the train station. Journal of Public Health, 38(2), e133–e137. <a href="https://doi.org/10.1093/pubmed/fdv096" target="_blank" rel="norefferer">https://doi.org/10.1093/pubmed/fdv096</a></p>
          <p id="14">[14] Blabst, N. & Diefenbach, S. (2017). WhatsApp and Wellbeing: A study on WhatsApp usage, communication quality and stress. Proceedings of the 31st International BCS Human Computer Interaction Conference. <a href="https://doi.org/10.14236/ewic/HCI2017.85" target="_blank" rel="norefferer">https://doi.org/10.14236/ewic/HCI2017.85</a></p>
          <p id="15">[15] Elhai, J. D., Yang, H. & Montag, C. (2021). Fear of missing out (FOMO): overview, theoretical underpinnings, and literature review on relations with severity of negative affectivity and problematic technology use. Brazilian Journal of Psychiatry, 43(2), 203–209. <a href="https://doi.org/10.1590/1516-4446-2020-0870" target="_blank" rel="norefferer">https://doi.org/10.1590/1516-4446-2020-0870</a></p>
          <p id="16">[16] Kuss, D. & Griffiths, M. (2017). Social Networking Sites and Addiction: Ten Lessons Learned. International Journal of Environmental Research and Public Health, 14(3), 311. <a href="https://doi.org/10.3390/ijerph14030311" target="_blank" rel="norefferer">https://doi.org/10.3390/ijerph14030311</a></p>
          <p id="17">[17] Alutaybi, A., McAlaney, J., Stefanidis, A., Phalp, K. T. & Ali, R. (2018). Designing social networks to combat fear of missing out. The 32nd Human Computer Interaction Conference.</p>
          <p id="18">[18] Instagram. (2018, 2. Juli). Introducing “You’re All Caught Up” in Feed. About Instagram. <a href="https://about.instagram.com/blog/announcements/introducing-youre-all-caught-up-in-feed" target="_blank" rel="norefferer">https://about.instagram.com/blog/announcements/introducing-youre-all-caught-up-in-feed</a></p>
          <p id="19">[19] Alutaybi, A., Arden-Close, E., McAlaney, J., Stefanidis, A., Phalp, K. & Ali, R. (2019). How Can Social Networks Design Trigger Fear of Missing Out? International Conference on Systems, Man and Cybernetics. <a href="https://doi.org/10.1109/SMC.2019.8914672" target="_blank" rel="norefferer">https://doi.org/10.1109/SMC.2019.8914672</a></p>
        </div>
      }
    ]
  }

  render() {
    return(
      <section className="bg-white rounded-2xl shadow-lg -mb-4">
        <div className="px-5">
          <h3 className="pt-10 text-center text-lg mb-8">Wissenschaft</h3>
          <h1 className="text-2xl sm:text-4xl lg:text-5xl text-center mb-8 font-bold">Blaue Häkchen und FoMO - Wie soziale Medien uns manipulieren</h1>
          <p className="text-lg text-center mb-8">Soziale Anwendungen wie WhatsApp oder Instagram sind darauf ausgelegt ihre NutzerInnen möglichst lange an den Bildschirm zu fesseln. Doch wie schaffen sie das und warum ist das problematisch?</p>
          <h3 className="py-2 px-6 bg-gray-200 mb-20 mx-auto w-fit rounded-full">Von Robert Sauter | 31.03.2022 | 5 Min Lesezeit</h3>
        </div>
        <article className="rounded-b-2xl pb-5">
          {
            this.content.map((paragraph, i) => {
              return <Paragraph key={i} title={ paragraph.title } background={ i % 2 === 0 ? 'bg-gray-100' : 'bg-white' }>{ paragraph.text }</Paragraph>
            })
          }
        </article>
      </section>
    );
  }
}
